### ISSUE TITLE
Support for code generation and automatic differentiation

### ISSUE THREAD

**Issue by jmirabel** [humanoid-path-planner/hpp-fcl#195]
After discussing with some users of hpp-fcl, I open this issue to track user requests. Please add you inputs if you have any.

**Comment by jcarpent** [comment]
In general, it would be nice indeed, but they are pro and cons:
- most of the algorithms for collision diction are based on if/then/else conditions to split the different cases (autodiff and code generation are really not good for that).
- basic primitives algorithms are simple enough and highly efficient. Using code generation would have no meaning.
- Autodiff on top of non-differentiable algorithms or solutions is something which needs more care than just overloading the code.
- finally, it would require a large refactorization of the current API to make it work well. I would rather suggest thinking theoretically how the collision problem has to be set up in order to recover a well-posed differentiability.
