### ISSUE TITLE
Qhull update submodule?

### ISSUE THREAD

**Issue by gianluigigrandesso** [humanoid-path-planner/hpp-fcl#333]
The Qhull commit is too old (2016) and it doesn't generate the cmake config files. @ManifoldFR

**Comment by ManifoldFR** [comment]
We noticed this while installing on a Ubuntu 18.04 system. Right now the CMake config for HPP expects a CMake config file for Qhull to be somewhere on the path. Qhull only generates such a file since [this commit](https://github.com/qhull/qhull/commit/925136ab82bce7fb45bf480ebc98cc68d3b88bfd)
This doesn't happen on systems where the apt package for Qhull installs the config file.

**Comment by jcarpent** [comment]
You should rather install qhull via apt or any package manager.
@jmirabel Could we remove the qhull version coming as a third party?

**Comment by jmirabel** [comment]
The original reason for having qhull as a submodule is that the version on apt official repo did not contain one of the required library to link against (I don't remember which one). I think the problem was reported somewhere and a fix was proposed. This was long ago (probably more than 5 years ago) so it may not be an issue anymore. If it is the case, then removing the submodule is the way to go.

**Comment by nim65s** [comment]
> Right now the CMake config for HPP expects a CMake config file for Qhull to be somewhere on the path.

I think if this CMake config file isn't found, we fallback to another strategy. Could you provide the exact error you get ?

**Comment by nim65s** [comment]
The submodule is here for people with a Qhull v7 from ubuntu 18.04 and 20.04 (to workaround https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925540) so I think it has to be on the same version. 

People on ubuntu 22.04 can have a Qhull v8 from their system, and in that case CMake will find the config file, and avoid building stuff from the submodule.

**Comment by jcarpent** [comment]
Fine with me. We can close this issue then.
