### ISSUE TITLE
Fix cmake export to allow cross-compilation with sysroot

### ISSUE THREAD

**Issue by aurelien-enchanted-tools** [humanoid-path-planner/hpp-fcl#542]
Hello,

Please fix the following:
```diff
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -256,8 +256,8 @@ ENDIF(octomap_FOUND)
 
 install(TARGETS ${LIBRARY_NAME}
   EXPORT ${TARGETS_EXPORT_NAME}
-  PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_FULL_INCLUDEDIR}
-  INCLUDES DESTINATION ${CMAKE_INSTALL_FULL_INCLUDEDIR}
-  LIBRARY DESTINATION ${CMAKE_INSTALL_FULL_LIBDIR}
-  ARCHIVE DESTINATION ${CMAKE_INSTALL_FULL_LIBDIR}
-  RUNTIME DESTINATION ${CMAKE_INSTALL_FULL_BINDIR})
+  PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
+  INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
+  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
+  ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
+  RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
```

**Comment by nim65s** [comment]
Hi @aurelien-enchanted-tools,
I would agree that installing in a relative path is better.

But this was added in https://github.com/humanoid-path-planner/hpp-fcl/pull/179 by @jcarpent to fix windows compilation, I don't exactly understand why. 

@jcarpent : is this still relevant ?

**Comment by jcarpent** [comment]
> Please fix the following:

Sorry @aurelien-enchanted-tools, I don't understand your request in such phrasing.
We are first and foremost real humans developing advanced and versatile open-source software. 
At minima, a thankful comment would have been appreciated, especially because you're using our tools for developing your product at Enchanted Tools. Don't you think so?

Related to your issue, could you elaborate more on the issue that you currently face with the CMake packaging of hpp-fcl?
